name: flutter_supabase_auth
description: A Flutter application with Supabase authentication
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.0.0
  flutter_svg: ^2.0.10+1
  geolocator: ^14.0.2
  intl: ^0.19.0
  google_maps_flutter: ^2.5.0
  geocoding: ^3.0.0
  url_launcher: ^6.2.4
  image_picker: ^1.0.4
  path: ^1.8.3
  fl_chart: ^1.1.0
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/